version: "3"

networks:
  frontend:
    driver: bridge
  database:
    driver: bridge

volumes:
  mariadb:
    driver: local
  phpmyadmin:
    driver: local

services:
  ### API ###################################################
  api:
    build:
      context: ./api
      args:
        - NODE_VERSION=${API_NODE_VERSION}
        - DB_HOST=${API_DB_HOST}
        - DB_PORT=${API_DB_PORT}
        - DB_DATABASE=${API_DB_DATABASE}
        - DB_USERNAME=${API_DB_USERNAME}
        - DB_PASSWORD=${API_DB_PASSWORD}
    ports:
      - "${API_PORT}:3000"
    environment:
      - JWT_SECRET=${API_JWT_SECRET}
      - DB_HOST=${API_DB_HOST}
      - DB_PORT=${API_DB_PORT}
      - DB_DATABASE=${API_DB_DATABASE}
      - DB_USERNAME=${API_DB_USERNAME}
      - DB_PASSWORD=${API_DB_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - frontend
      - database

  ### WEB ###################################################
  web:
    build:
      context: ./web
      args:
        - NODE_VERSION=${API_NODE_VERSION}
        - VUE_APP_API_BASE_URL=${WEB_API_BASE_URL}
    ports:
      - "${WEB_PORT}:8080"
    depends_on:
      - api
    networks:
      - frontend

  ### MariaDB ###############################################
  mariadb:
    build:
      context: ./docker/mariadb
      args:
        - MARIADB_VERSION=${MARIADB_VERSION}
    volumes:
      - ${DATA_PATH_HOST}/mariadb:/var/lib/mysql
    ports:
      - "${MARIADB_PORT}:3306"
    environment:
      - TZ=America/Sao_Paulo
      - MYSQL_DATABASE=${MARIADB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
    networks:
      - database

  ### phpMyAdmin ############################################
  phpmyadmin:
    build: ./docker/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${PMA_USER}
      - MYSQL_PASSWORD=${PMA_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${PMA_ROOT_PASSWORD}
    ports:
      - "${PMA_PORT}:80"
    depends_on:
      - mariadb
    networks:
      - database
